### PR TITLE
Replace gca with metadata in voucher server doc

### PR DESCRIPTION
**Pull request by ooq**
This cleans server doc following changes in #70

### CODE REVIEW

**Comment by ooq** [comment]
@catherinejones @Nilay-Shah Can you take a look?

**Review by Nilay-Shah — DISMISSED** [review]
Looks good! Do we also want to have something to say that `g` and `gca` are supported but are deprecated in favour of `metadata`?

**Review by catherinejones — APPROVED** [review]
Looks good to me! @ooq should we do a PR from shopify/voucher to grafeas/voucher once the cleanup has finished or should we be pushing the shopify version to grafeas/voucher directly?

**Comment by ooq** [comment]
> Looks good! Do we also want to have something to say that `g` and `gca` are supported but are deprecated in favour of `metadata`?

Done!

**Comment by ooq** [comment]
@catherinejones Let's do PRs for the outstanding works in this repo once they are in?

**Review by catherinejones — APPROVED** [review]

**Comment by catherinejones** [comment]
@ooq Sounds good to me! Please feel free to Squash and Merge once CI passes!

**Comment by ooq** [comment]
@catherinejones Is `Travis CI - Branch` halted?

**Comment by catherinejones** [comment]
Whoops, sorry @ooq it wasn't running because your branch didn't exist on the Git server. I've removed that check from the requirements for pull requests! You should be able to merge now!

**Comment by ooq** [comment]
Still says `Only those with write access to this repository can merge pull requests.` I'll squash it so that you can merge it?

**Review by Nilay-Shah — APPROVED** [review]

**Pull request merged**
