### PR TITLE
Add additional check metrics

### PR DESCRIPTION
**Pull request by catherinejones**
Adds additional metrics for Checks and Attestations. This will help us compare number of checks failing to number of checks that are run.

### CODE REVIEW

**Review by klautcomputing — DISMISSED** [review]
My name is @klautcomputing and I approve this PR.

**Review by Nilay-Shah — DISMISSED** [review]

**Review by rxbchen — APPROVED** [review]
LGTM!

**Review by klautcomputing — APPROVED** [review]
:shipit:

**Review by Nilay-Shah — APPROVED** [review]

**Review by rxbchen — APPROVED** [review]
💯

**Pull request merged**
